-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 16:49:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema callfi_officeman
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `callfi_officeman` ;

-- -----------------------------------------------------
-- Schema callfi_officeman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `callfi_officeman` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `callfi_officeman` ;

-- -----------------------------------------------------
-- Table `callfi_officeman`.`ent_catc_corpgroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`ent_catc_corpgroups` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`ent_catc_corpgroups` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`ent_catc_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`ent_catc_companies` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`ent_catc_companies` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CORPGROUP_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ent_catc_companies_ent_catc_corpgroups1_idx` (`CORPGROUP_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_ent_catc_companies_ent_catc_corpgroups1`
    FOREIGN KEY (`CORPGROUP_ID`)
    REFERENCES `callfi_officeman`.`ent_catc_corpgroups` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`ent_catc_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`ent_catc_areas` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`ent_catc_areas` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `CODE` VARCHAR(3) NULL DEFAULT NULL,
  `PARENT_ID` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ent_catc_areas_ent_catc_companies1_idx` (`COMPANY_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_ent_catc_areas_ent_catc_companies1`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `callfi_officeman`.`ent_catc_companies` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_catc_genders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_catc_genders` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_catc_genders` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_catc_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_catc_jobs` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_catc_jobs` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `CODE` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_catc_titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_catc_titles` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_catc_titles` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `DISPLAY` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_cate_enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_cate_enrollment` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_cate_enrollment` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_cats_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_cats_employee` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_cats_employee` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_catc_countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_catc_countries` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_catc_countries` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `OFFICIAL_NAME` VARCHAR(100) NOT NULL,
  `ISO_A2` VARCHAR(2) NOT NULL,
  `ISO_A3` VARCHAR(20) NOT NULL,
  `ISO_NUM` INT(3) NOT NULL,
  `TLD` VARCHAR(2) NOT NULL,
  `SOVEREIGN` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_catc_provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_catc_provinces` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_catc_provinces` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `CODE` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_loc_catc_entfeds_loc_catc_countries_idx` (`COUNTRY_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_loc_catc_entfeds_loc_catc_countries`
    FOREIGN KEY (`COUNTRY_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_countries` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_catc_zipcodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_catc_zipcodes` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_catc_zipcodes` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROVINCE_ID` INT UNSIGNED NOT NULL,
  `ZIPCODE` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_loc_catc_zipcodes_loc_catc_provinces1_idx` (`PROVINCE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_loc_catc_zipcodes_loc_catc_provinces1`
    FOREIGN KEY (`PROVINCE_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_provinces` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_catc_settlement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_catc_settlement` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_catc_settlement` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `ZIPCODE_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_loc_catc_settlement_loc_catc_zipcodes1_idx` (`ZIPCODE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_loc_catc_settlement_loc_catc_zipcodes1`
    FOREIGN KEY (`ZIPCODE_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_zipcodes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_catc_emplocations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_catc_emplocations` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_catc_emplocations` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_catt_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_catt_employee` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_catt_employee` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_data_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_data_employees` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_data_employees` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `AREA_ID` INT UNSIGNED NOT NULL,
  `JOB_ID` INT UNSIGNED NOT NULL,
  `AREA_BOSS` TINYINT(1) NOT NULL DEFAULT 0,
  `EMPLOC_ID` INT UNSIGNED NOT NULL,
  `STATION` VARCHAR(20) NULL,
  `GENDER_ID` INT UNSIGNED NOT NULL,
  `TITLE_ID` INT UNSIGNED NOT NULL,
  `SURNAME` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `MIDNAME` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `LASTNAME_1` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `LASTNAME_2` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `BIRTHDATE` DATE NOT NULL,
  `PHONE_PRIV` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `PHONE_WORK` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `MAIL_PRIV` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `MAIL_WORK` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SETTLEMENT_ID` INT UNSIGNED NOT NULL,
  `ADDRESS_1` VARCHAR(50) NULL,
  `ADDRESS_2` VARCHAR(50) NULL,
  `DNI` VARCHAR(20) NULL,
  `SSN` VARCHAR(20) NULL,
  `RFC_MEX` VARCHAR(13) NULL,
  `ENROLL_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ENROLL_NUM` INT NOT NULL DEFAULT '1',
  `STATUS_ID` INT UNSIGNED NOT NULL,
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_hr_data_employees_hr_catc_jobs1_idx` (`JOB_ID` ASC) VISIBLE,
  INDEX `fk_hr_data_employees_hr_catc_titles1_idx` (`TITLE_ID` ASC) VISIBLE,
  INDEX `fk_hr_data_employees_hr_catc_genders1_idx` (`GENDER_ID` ASC) VISIBLE,
  INDEX `fk_hr_data_employees_hr_cats_employee1_idx` (`STATUS_ID` ASC) VISIBLE,
  INDEX `fk_hr_data_employees_loc_catc_settlement1_idx` (`SETTLEMENT_ID` ASC) VISIBLE,
  INDEX `fk_hr_data_employees_ent_catc_areas1_idx` (`AREA_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_hr_data_employees_loc_catc_emplocations1_idx` (`EMPLOC_ID` ASC) VISIBLE,
  INDEX `fk_hr_data_employees_hr_catt_employee1_idx` (`TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_hr_data_employees_hr_catc_jobs1`
    FOREIGN KEY (`JOB_ID`)
    REFERENCES `callfi_officeman`.`hr_catc_jobs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_data_employees_hr_catc_titles1`
    FOREIGN KEY (`TITLE_ID`)
    REFERENCES `callfi_officeman`.`hr_catc_titles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_data_employees_hr_catc_genders1`
    FOREIGN KEY (`GENDER_ID`)
    REFERENCES `callfi_officeman`.`hr_catc_genders` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_data_employees_hr_cats_employee1`
    FOREIGN KEY (`STATUS_ID`)
    REFERENCES `callfi_officeman`.`hr_cats_employee` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_data_employees_loc_catc_settlement1`
    FOREIGN KEY (`SETTLEMENT_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_settlement` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_data_employees_ent_catc_areas1`
    FOREIGN KEY (`AREA_ID`)
    REFERENCES `callfi_officeman`.`ent_catc_areas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_data_employees_loc_catc_emplocations1`
    FOREIGN KEY (`EMPLOC_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_emplocations` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_data_employees_hr_catt_employee1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`hr_catt_employee` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_hist_employee_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_hist_employee_data` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_hist_employee_data` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_UUID` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CONSEC` INT NOT NULL,
  `TABLE_NAME` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `FIELD_NAME` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `VALUE_OLD` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `VALUE_NEW` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `USER_UUID` VARCHAR(30) NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_hist_employee_enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_hist_employee_enrollment` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_hist_employee_enrollment` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_UUID` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CONSEC` INT NOT NULL,
  `EVENT_ID` INT UNSIGNED NOT NULL,
  `USER_UUID` VARCHAR(30) NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_hr_hist_employee_enrollment_hr_cate_enrollment1_idx` (`EVENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_hr_hist_employee_enrollment_hr_cate_enrollment1`
    FOREIGN KEY (`EVENT_ID`)
    REFERENCES `callfi_officeman`.`hr_cate_enrollment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_brands` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_brands` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `CODE` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catq_equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catq_equipment` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catq_equipment` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_models` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_models` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BRAND_ID` INT UNSIGNED NOT NULL,
  `CLASS_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(200) NOT NULL,
  `NUMBER` VARCHAR(200) NULL DEFAULT NULL,
  `YEAR` YEAR NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_catc_models_inv_catc_brands1_idx` (`BRAND_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_inv_catc_models_inv_catq_equipment1_idx` (`CLASS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_catc_models_inv_catc_brands1`
    FOREIGN KEY (`BRAND_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_brands` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_catc_models_inv_catq_equipment1`
    FOREIGN KEY (`CLASS_ID`)
    REFERENCES `callfi_officeman`.`inv_catq_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_cats_equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_cats_equipment` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_cats_equipment` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catt_equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catt_equipment` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catt_equipment` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CODE` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PREFIX` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_conditions` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_conditions` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_data_equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_data_equipment` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_data_equipment` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(30) NOT NULL,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `CONSEC` INT NOT NULL,
  `MODEL_ID` INT UNSIGNED NOT NULL,
  `SERIAL_NUM` VARCHAR(100) NULL DEFAULT NULL,
  `IS_COMPUTER` TINYINT(1) NOT NULL DEFAULT 0,
  `CONDITION_ID` INT UNSIGNED NOT NULL,
  `STATUS_ID` INT UNSIGNED NOT NULL,
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_data_equipment_inv_catc_models1_idx` (`MODEL_ID` ASC) VISIBLE,
  INDEX `fk_inv_data_equipment_inv_catt_equipment1_idx` (`TYPE_ID` ASC) VISIBLE,
  INDEX `fk_inv_data_equipment_inv_cats_equipment1_idx` (`STATUS_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_inv_data_equipment_inv_catc_conditions1_idx` (`CONDITION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_data_equipment_inv_catc_models1`
    FOREIGN KEY (`MODEL_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_models` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_data_equipment_inv_catt_equipment1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`inv_catt_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_data_equipment_inv_cats_equipment1`
    FOREIGN KEY (`STATUS_ID`)
    REFERENCES `callfi_officeman`.`inv_cats_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_data_equipment_inv_catc_conditions1`
    FOREIGN KEY (`CONDITION_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_conditions` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catc_privileges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catc_privileges` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catc_privileges` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL DEFAULT NULL,
  `FOR_ADMINS` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catc_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catc_groups` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catc_groups` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catt_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catt_user` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catt_user` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_data_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_data_users` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_data_users` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(30) NOT NULL,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `USERNAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(200) NOT NULL,
  `IS_ADMIN` TINYINT(1) NOT NULL DEFAULT 0,
  `ENABLED` TINYINT(1) NOT NULL DEFAULT 0,
  `DESCRIPTION` VARCHAR(200) NULL,
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_sys_data_users_sys_catt_user1_idx` (`TYPE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_sys_data_users_sys_catt_user1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`sys_catt_user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_rels_user_privs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_rels_user_privs` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_rels_user_privs` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ENABLED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_rels_rol_privs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_rels_rol_privs` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_rels_rol_privs` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ENABLED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catt_software`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catt_software` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catt_software` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_software`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_software` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_software` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BRAND_ID` INT UNSIGNED NOT NULL,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `VERSION` VARCHAR(10) NULL,
  `YEAR` YEAR NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_catc_software_inv_catc_brands1_idx` (`BRAND_ID` ASC) VISIBLE,
  INDEX `fk_inv_catc_software_inv_catt_software1_idx` (`TYPE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_catc_software_inv_catc_brands1`
    FOREIGN KEY (`BRAND_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_brands` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_catc_software_inv_catt_software1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`inv_catt_software` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_cpus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_cpus` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_cpus` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BRAND_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(20) NOT NULL,
  `GEN` INT NULL,
  `BUILD` VARCHAR(15) NULL,
  `YEAR` YEAR NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_catc_processors_inv_catc_brands1_idx` (`BRAND_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_catc_processors_inv_catc_brands1`
    FOREIGN KEY (`BRAND_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_brands` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_rams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_rams` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_rams` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catt_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catt_storage` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catt_storage` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catt_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catt_login` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catt_login` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_data_logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_data_logins` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_data_logins` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `USERNAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(20) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_data_logins_inv_catt_login1_idx` (`TYPE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_data_logins_inv_catt_login1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`inv_catt_login` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_data_computers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_data_computers` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_data_computers` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EQUIPMENT_ID` INT UNSIGNED NOT NULL,
  `CPU_ID` INT UNSIGNED NOT NULL,
  `CPU_SPEED` DECIMAL(6,3) NOT NULL,
  `RAM_TYPE` INT UNSIGNED NOT NULL,
  `RAM_SIZE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_data_computers_inv_catc_cpus1_idx` (`CPU_ID` ASC) VISIBLE,
  INDEX `fk_inv_data_computers_inv_catc_ram1_idx` (`RAM_TYPE` ASC) VISIBLE,
  INDEX `fk_inv_data_computers_inv_data_equipment1_idx` (`EQUIPMENT_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_data_computers_inv_catc_cpus1`
    FOREIGN KEY (`CPU_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_cpus` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_data_computers_inv_catc_ram1`
    FOREIGN KEY (`RAM_TYPE`)
    REFERENCES `callfi_officeman`.`inv_catc_rams` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_data_computers_inv_data_equipment1`
    FOREIGN KEY (`EQUIPMENT_ID`)
    REFERENCES `callfi_officeman`.`inv_data_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_storage` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_storage` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  `REMOVABLE` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_catc_storage_inv_catt_storage1_idx` (`TYPE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_catc_storage_inv_catt_storage1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`inv_catt_storage` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_rels_computer_logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_rels_computer_logins` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_rels_computer_logins` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `COMPUTER_ID` INT UNSIGNED NOT NULL,
  `LOGIN_ID` INT UNSIGNED NOT NULL,
  `ENABLED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_rels_computer_logins_inv_data_computers1_idx` (`COMPUTER_ID` ASC) VISIBLE,
  INDEX `fk_inv_rels_computer_logins_inv_data_logins1_idx` (`LOGIN_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_rels_computer_logins_inv_data_computers1`
    FOREIGN KEY (`COMPUTER_ID`)
    REFERENCES `callfi_officeman`.`inv_data_computers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_rels_computer_logins_inv_data_logins1`
    FOREIGN KEY (`LOGIN_ID`)
    REFERENCES `callfi_officeman`.`inv_data_logins` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_rels_computer_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_rels_computer_storage` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_rels_computer_storage` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `COMPUTER_ID` INT UNSIGNED NOT NULL,
  `STORAGE_ID` INT UNSIGNED NOT NULL,
  `SIZE_MB` DECIMAL(10,4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_rels_computer_storage_inv_data_computers1_idx` (`COMPUTER_ID` ASC) VISIBLE,
  INDEX `fk_inv_rels_computer_storage_inv_catc_storage1_idx` (`STORAGE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_rels_computer_storage_inv_data_computers1`
    FOREIGN KEY (`COMPUTER_ID`)
    REFERENCES `callfi_officeman`.`inv_data_computers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_rels_computer_storage_inv_catc_storage1`
    FOREIGN KEY (`STORAGE_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_storage` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_rels_computer_software`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_rels_computer_software` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_rels_computer_software` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `COMPUTER_ID` INT UNSIGNED NOT NULL,
  `SOFTWARE_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_rels_computer_software_inv_data_computers1_idx` (`COMPUTER_ID` ASC) VISIBLE,
  INDEX `fk_inv_rels_computer_software_inv_catc_software1_idx` (`SOFTWARE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_rels_computer_software_inv_data_computers1`
    FOREIGN KEY (`COMPUTER_ID`)
    REFERENCES `callfi_officeman`.`inv_data_computers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_rels_computer_software_inv_catc_software1`
    FOREIGN KEY (`SOFTWARE_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_software` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_link_employee_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_link_employee_user` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_link_employee_user` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` INT UNSIGNED NOT NULL,
  `EMPLOYEE_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_sys_link_employee_user_sys_data_users1_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_sys_link_employee_user_hr_data_employees1_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_sys_link_employee_user_sys_data_users1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `callfi_officeman`.`sys_data_users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_link_employee_user_hr_data_employees1`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `callfi_officeman`.`hr_data_employees` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_specs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_specs` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_specs` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EQUIP_TYPE` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_catc_specs_inv_catt_equipment1_idx` (`EQUIP_TYPE` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_catc_specs_inv_catt_equipment1`
    FOREIGN KEY (`EQUIP_TYPE`)
    REFERENCES `callfi_officeman`.`inv_catt_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_rels_equipment_specs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_rels_equipment_specs` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_rels_equipment_specs` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EQUIPMENT_ID` INT UNSIGNED NOT NULL,
  `SPEC_ID` INT UNSIGNED NOT NULL,
  `VALUE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_rels_equipment_specs_inv_data_equipment1_idx` (`EQUIPMENT_ID` ASC) VISIBLE,
  INDEX `fk_inv_rels_equipment_specs_inv_catc_specs1_idx` (`SPEC_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_rels_equipment_specs_inv_data_equipment1`
    FOREIGN KEY (`EQUIPMENT_ID`)
    REFERENCES `callfi_officeman`.`inv_data_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_rels_equipment_specs_inv_catc_specs1`
    FOREIGN KEY (`SPEC_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_specs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catc_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catc_modules` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catc_modules` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `STR_ALIAS` VARCHAR(20) NOT NULL,
  `PREFIX` VARCHAR(5) NOT NULL,
  `CODE` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catt_note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catt_note` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catt_note` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MODULE` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  `SEVERITY` INT NOT NULL DEFAULT 0,
  `ICON` VARCHAR(10) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_sys_catt_note_sys_catc_modules1_idx` (`MODULE` ASC) VISIBLE,
  CONSTRAINT `fk_sys_catt_note_sys_catc_modules1`
    FOREIGN KEY (`MODULE`)
    REFERENCES `callfi_officeman`.`sys_catc_modules` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_data_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_data_notes` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_data_notes` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EQUIPMENT_ID` INT UNSIGNED NOT NULL,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `TITLE` VARCHAR(100) NULL,
  `NOTE` TEXT NOT NULL,
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_data_notes_inv_data_equipment1_idx` (`EQUIPMENT_ID` ASC) VISIBLE,
  INDEX `fk_inv_data_notes_sys_catt_note1_idx` (`TYPE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_data_notes_inv_data_equipment1`
    FOREIGN KEY (`EQUIPMENT_ID`)
    REFERENCES `callfi_officeman`.`inv_data_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_data_notes_sys_catt_note1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`sys_catt_note` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catt_assign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catt_assign` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catt_assign` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_data_assigns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_data_assigns` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_data_assigns` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `EQUIPMENT_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_data_assigns_inv_catt_assign1_idx` (`TYPE_ID` ASC) VISIBLE,
  INDEX `fk_inv_data_assigns_inv_data_equipment1_idx` (`EQUIPMENT_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_data_assigns_inv_catt_assign1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`inv_catt_assign` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_data_assigns_inv_data_equipment1`
    FOREIGN KEY (`EQUIPMENT_ID`)
    REFERENCES `callfi_officeman`.`inv_data_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_link_assign_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_link_assign_employee` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_link_assign_employee` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ASSIGN_ID` INT UNSIGNED NOT NULL,
  `EMPLOYEE_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_link_assign_employee_inv_data_assigns1_idx` (`ASSIGN_ID` ASC) VISIBLE,
  INDEX `fk_inv_link_assign_employee_hr_data_employees1_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_link_assign_employee_inv_data_assigns1`
    FOREIGN KEY (`ASSIGN_ID`)
    REFERENCES `callfi_officeman`.`inv_data_assigns` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_link_assign_employee_hr_data_employees1`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `callfi_officeman`.`hr_data_employees` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_link_assign_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_link_assign_area` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_link_assign_area` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ASSIGN_ID` INT UNSIGNED NOT NULL,
  `AREA_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_inv_link_assign_area_inv_data_assigns1_idx` (`ASSIGN_ID` ASC) VISIBLE,
  INDEX `fk_inv_link_assign_area_ent_catc_areas1_idx` (`AREA_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_link_assign_area_inv_data_assigns1`
    FOREIGN KEY (`ASSIGN_ID`)
    REFERENCES `callfi_officeman`.`inv_data_assigns` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_link_assign_area_ent_catc_areas1`
    FOREIGN KEY (`AREA_ID`)
    REFERENCES `callfi_officeman`.`ent_catc_areas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`hr_data_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`hr_data_notes` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`hr_data_notes` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` INT UNSIGNED NOT NULL,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `TITLE` VARCHAR(100) NULL,
  `NOTE` TEXT NOT NULL,
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_hr_data_notes_hr_data_employees1_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  INDEX `fk_hr_data_notes_sys_catt_note1_idx` (`TYPE_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_hr_data_notes_hr_data_employees1`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `callfi_officeman`.`hr_data_employees` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_data_notes_sys_catt_note1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`sys_catt_note` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_catc_facilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_catc_facilities` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_catc_facilities` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  `SETTLEMENT_ID` INT UNSIGNED NOT NULL,
  `ADDRESS_1` VARCHAR(50) NULL,
  `ADDRESS_2` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_loc_catc_facilities_loc_catc_settlement1_idx` (`SETTLEMENT_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_loc_catc_facilities_loc_catc_settlement1`
    FOREIGN KEY (`SETTLEMENT_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_settlement` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_rels_areas_facilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_rels_areas_facilities` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_rels_areas_facilities` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FACILITY_ID` INT UNSIGNED NOT NULL,
  `AREA_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  `INTERNAL_LOCATION` VARCHAR(50) NULL,
  `STATIONS_QTY` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_loc_rels_areas_facilities_loc_catc_facilities1_idx` (`FACILITY_ID` ASC) VISIBLE,
  INDEX `fk_loc_rels_areas_facilities_ent_catc_areas1_idx` (`AREA_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_loc_rels_areas_facilities_loc_catc_facilities1`
    FOREIGN KEY (`FACILITY_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_facilities` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loc_rels_areas_facilities_ent_catc_areas1`
    FOREIGN KEY (`AREA_ID`)
    REFERENCES `callfi_officeman`.`ent_catc_areas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_catc_currencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_catc_currencies` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_catc_currencies` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `ISO_A3` VARCHAR(3) NOT NULL,
  `ISO_NUM` INT(3) NOT NULL,
  `NOTES` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_rels_currency_rates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_rels_currency_rates` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_rels_currency_rates` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CURRENCY_FROM` INT UNSIGNED NOT NULL,
  `CURRENCY_TO` INT UNSIGNED NOT NULL,
  `RATE` DECIMAL(20,5) NOT NULL DEFAULT 1,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_loc_rels_currency_rates_loc_catc_currencies1_idx` (`CURRENCY_FROM` ASC) VISIBLE,
  INDEX `fk_loc_rels_currency_rates_loc_catc_currencies2_idx` (`CURRENCY_TO` ASC) VISIBLE,
  CONSTRAINT `fk_loc_rels_currency_rates_loc_catc_currencies1`
    FOREIGN KEY (`CURRENCY_FROM`)
    REFERENCES `callfi_officeman`.`loc_catc_currencies` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loc_rels_currency_rates_loc_catc_currencies2`
    FOREIGN KEY (`CURRENCY_TO`)
    REFERENCES `callfi_officeman`.`loc_catc_currencies` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_hist_currency_rates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_hist_currency_rates` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_hist_currency_rates` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ISO_A3_FROM` VARCHAR(3) NOT NULL,
  `ISO_A3_TO` VARCHAR(3) NOT NULL,
  `RATE` DECIMAL(20,5) NOT NULL DEFAULT 1,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_catc_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_catc_languages` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_catc_languages` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `ISO_A2` VARCHAR(2) NOT NULL,
  `ISO_A3` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catq_interface`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catq_interface` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catq_interface` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catc_interfaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catc_interfaces` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catc_interfaces` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  `CLASS_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_inv_catc_interfaces_inv_catq_interface1_idx` (`CLASS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_catc_interfaces_inv_catq_interface1`
    FOREIGN KEY (`CLASS_ID`)
    REFERENCES `callfi_officeman`.`inv_catq_interface` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_catt_connector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_catt_connector` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_catt_connector` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`inv_rels_equipment_interfaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`inv_rels_equipment_interfaces` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`inv_rels_equipment_interfaces` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EQUIPMENT_ID` INT UNSIGNED NOT NULL,
  `INTERFACE_ID` INT UNSIGNED NOT NULL,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `IN_OUT` CHAR(1) NOT NULL DEFAULT 'I',
  `QTY` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_inv_rels_equipment_interfaces_inv_data_equipment1_idx` (`EQUIPMENT_ID` ASC) VISIBLE,
  INDEX `fk_inv_rels_equipment_interfaces_inv_catc_interfaces1_idx` (`INTERFACE_ID` ASC) VISIBLE,
  INDEX `fk_inv_rels_equipment_interfaces_inv_catt_connector1_idx` (`TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_inv_rels_equipment_interfaces_inv_data_equipment1`
    FOREIGN KEY (`EQUIPMENT_ID`)
    REFERENCES `callfi_officeman`.`inv_data_equipment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_rels_equipment_interfaces_inv_catc_interfaces1`
    FOREIGN KEY (`INTERFACE_ID`)
    REFERENCES `callfi_officeman`.`inv_catc_interfaces` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_rels_equipment_interfaces_inv_catt_connector1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`inv_catt_connector` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catt_param`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catt_param` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catt_param` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `STR_ALIAS` VARCHAR(20) NOT NULL,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catt_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catt_value` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catt_value` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catc_params`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catc_params` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catc_params` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MODULE_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(20) NOT NULL,
  `STR_ALIAS` VARCHAR(20) NOT NULL,
  `TYPE_ID` INT UNSIGNED NOT NULL,
  `VALUE_TYPE` INT UNSIGNED NOT NULL,
  `VALUE_DEF` VARCHAR(200) NULL,
  `VALUE_GLOBAL` VARCHAR(200) NULL,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_sys_catc_params_sys_catc_modules1_idx` (`MODULE_ID` ASC) VISIBLE,
  INDEX `fk_sys_catc_params_sys_catt_param1_idx` (`TYPE_ID` ASC) VISIBLE,
  INDEX `fk_sys_catc_params_sys_catt_value1_idx` (`VALUE_TYPE` ASC) VISIBLE,
  CONSTRAINT `fk_sys_catc_params_sys_catc_modules1`
    FOREIGN KEY (`MODULE_ID`)
    REFERENCES `callfi_officeman`.`sys_catc_modules` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_catc_params_sys_catt_param1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `callfi_officeman`.`sys_catt_param` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_catc_params_sys_catt_value1`
    FOREIGN KEY (`VALUE_TYPE`)
    REFERENCES `callfi_officeman`.`sys_catt_value` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_rels_user_params`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_rels_user_params` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_rels_user_params` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PARAM_ID` INT UNSIGNED NOT NULL,
  `USER_ID` INT UNSIGNED NOT NULL,
  `VALUE_USER` VARCHAR(200) NULL,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_sys_rels_user_params_sys_catc_params1_idx` (`PARAM_ID` ASC) VISIBLE,
  INDEX `fk_sys_rels_user_params_sys_data_users1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_sys_rels_user_params_sys_catc_params1`
    FOREIGN KEY (`PARAM_ID`)
    REFERENCES `callfi_officeman`.`sys_catc_params` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_rels_user_params_sys_data_users1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `callfi_officeman`.`sys_data_users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catc_scripts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catc_scripts` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catc_scripts` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `STR_ALIAS` VARCHAR(20) NOT NULL,
  `PATH` VARCHAR(500) NOT NULL,
  `FILENAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` TEXT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_tmpt_schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_tmpt_schedules` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_tmpt_schedules` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `STR_ALIAS` VARCHAR(20) NOT NULL,
  `YEAR` INT(4) NOT NULL DEFAULT -1,
  `MONTH` INT(2) NOT NULL DEFAULT -1,
  `DAY_M` INT(2) NOT NULL DEFAULT -1,
  `DAY_W` INT(1) NOT NULL DEFAULT -1,
  `WDAY` TINYINT(1) NOT NULL DEFAULT 1,
  `WEND` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_catc_schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_catc_schedules` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_catc_schedules` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `STR_ALIAS` VARCHAR(20) NOT NULL,
  `YEAR` INT(4) NOT NULL DEFAULT -1,
  `MONTH` INT(2) NOT NULL DEFAULT -1,
  `DAY_M` INT(2) NOT NULL DEFAULT -1,
  `DAY_W` INT(1) NOT NULL DEFAULT -1,
  `WDAY` TINYINT(1) NOT NULL DEFAULT 1,
  `WEND` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_data_cronjobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_data_cronjobs` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_data_cronjobs` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(30) NOT NULL,
  `SCRIPT_ID` INT UNSIGNED NOT NULL,
  `SCHEDULE_ID` INT UNSIGNED NOT NULL,
  `HOUR` TIME NOT NULL DEFAULT '00:00:00.0000',
  `RUN_ONCE` TINYINT(1) NOT NULL DEFAULT 0,
  `RUN_LAST` TIMESTAMP NULL,
  `RUN_NEXT` TIMESTAMP NULL,
  `RUN_SUCCESS` TINYINT(1) NOT NULL DEFAULT 0,
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_sys_data_cronjobs_sys_catc_scripts1_idx` (`SCRIPT_ID` ASC) VISIBLE,
  INDEX `fk_sys_data_cronjobs_sys_catc_schedules1_idx` (`SCHEDULE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_sys_data_cronjobs_sys_catc_scripts1`
    FOREIGN KEY (`SCRIPT_ID`)
    REFERENCES `callfi_officeman`.`sys_catc_scripts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_data_cronjobs_sys_catc_schedules1`
    FOREIGN KEY (`SCHEDULE_ID`)
    REFERENCES `callfi_officeman`.`sys_catc_schedules` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`sys_hist_cronjobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`sys_hist_cronjobs` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`sys_hist_cronjobs` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CRON_UUID` VARCHAR(30) NOT NULL,
  `SUCCESS` TINYINT(1) NOT NULL DEFAULT 0,
  `EXIT_CODE` INT NOT NULL DEFAULT 0,
  `EXIT_MSG` VARCHAR(100) NULL,
  `EXIT_DETAILS` TEXT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_rels_countries_currencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_rels_countries_currencies` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_rels_countries_currencies` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID` INT UNSIGNED NOT NULL,
  `CURRENCY_ID` INT UNSIGNED NOT NULL,
  `COUNTRY_MAIN` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_loc_rels_countries_currencies_loc_catc_currencies1_idx` (`CURRENCY_ID` ASC) VISIBLE,
  INDEX `fk_loc_rels_countries_currencies_loc_catc_countries1_idx` (`COUNTRY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_loc_rels_countries_currencies_loc_catc_currencies1`
    FOREIGN KEY (`CURRENCY_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_currencies` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loc_rels_countries_currencies_loc_catc_countries1`
    FOREIGN KEY (`COUNTRY_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_countries` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`loc_rels_countries_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`loc_rels_countries_languages` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`loc_rels_countries_languages` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID` INT UNSIGNED NOT NULL,
  `LANGUAGE_ID` INT UNSIGNED NOT NULL,
  `COUNTRY_MAIN` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_loc_rels_countries_languages_loc_catc_countries1_idx` (`COUNTRY_ID` ASC) VISIBLE,
  INDEX `fk_loc_rels_countries_languages_loc_catc_languages1_idx` (`LANGUAGE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_loc_rels_countries_languages_loc_catc_countries1`
    FOREIGN KEY (`COUNTRY_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_countries` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loc_rels_countries_languages_loc_catc_languages1`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `callfi_officeman`.`loc_catc_languages` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `callfi_officeman`.`ent_tmpt_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `callfi_officeman`.`ent_tmpt_areas` ;

CREATE TABLE IF NOT EXISTS `callfi_officeman`.`ent_tmpt_areas` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `CODE` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
